### ISSUE TITLE
Removing callback with "off" method doesn’t work

### ISSUE THREAD

**Issue by niksy** [weblinc/pointbreak.js#1]
If you try to remove specific callback with "off" method (e.g. `PointBreak.get('small').off('match', someCallback)`, it won’t work since it compares callback content to listener object, but it should compare it to listener’s `callback` property.

Also, splicing `listeners` array changes the content of array so iteration won’t work if you reach last element. I suggest setting callback to some noop method, or setting element of array to `null` or `undefined` and then later remove those elements with another iteration method.

I can make PR with the suggestions and then you can see if it works for you.

**Comment by knightdr** [comment]
@niksy 

Have a look. I've merged in a patch for this issue. Thanks for reporting the bug.

**Comment by niksy** [comment]
LGTM :+1:
